Cajal Body Figure

```{r, fig.height=3.5, fig.width=3.5}
HCT116 <- c(rep(0:0,len=6),rep(1:1,len=8),rep(2:2,len=39),rep(3:3,len=72),rep(4:4,len=68),rep(5:5,len=26),rep(6:6,len=14),rep(7:7,len=4),rep(8:8,len=2),rep(9:9,len=1))
UL1 <- c(rep(0:0,len=112),rep(1:1,len=69),rep(2:2,len=46),rep(3:3,len=10),rep(4:4,len=3))

cbodies <- as.data.frame(HCT116)
cbodies1 <- as.data.frame(UL1)
                          
cbodies$Sample <- "HCT116"
cbodies1$Sample <- "hnRNPUL1"
names(cbodies1)[1] <- "CB/cell"
names(cbodies)[1] <- "CB/cell"

violin <- rbind(cbodies,cbodies1)

t.test(violin$`CB/cell`[violin$Sample=="HCT116"], violin$`CB/cell`[violin$Sample=="hnRNPUL1"])

library(ggplot2)
library(dplyr)
library(stringr)
cbbPalette <- c( "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")


violin%>%
  ggplot+
  aes(x=Sample,y=`CB/cell`,fill=Sample)+
  ylab("Cajal Bodies / Cell")+
   guides(fill=FALSE,color=FALSE)+
  theme_bw()+
  coord_cartesian(ylim=c(0,10.75))+
  scale_fill_manual(values=cbbPalette)+
  geom_violin(trim=TRUE,adjust=3,alpha=0.8)+
  geom_boxplot(width=.95,color="black",fill="white",alpha=0.5,outlier.shape=NA)+
  geom_segment(aes(x = 1, y = 10.5, xend = 2, yend = 10.5),size=0.5) +
  annotate("text",x = 1.5, y = 10.75, label = "***", size = 5) +
  geom_segment(aes(x = 1, y = 10.54, xend = 1, yend = 9.5))+ 
  geom_segment(aes(x = 2, y = 10.54, xend = 2, yend = 9.5))+
  theme(axis.title.x=element_blank(),
  axis.text.x=element_text(size=14),
  axis.text.y=element_text(size=14),
  axis.title.y=element_text(margin=margin(t=0,r=10,b=0,l=0)),
  text=element_text(size=17))
ggsave(file=".//Cbodies.png",dpi=300,units="in",width=3.5,height=3.5)
```

SART3 FOCI
```{r, fig.height=3.5, fig.width=3.5}
HCT116 <- c(rep(0:0,len=90),rep(1:1,len=66),rep(2:2,len=37),rep(3:3,len=11),rep(4:4,len=6))
UL1 <- c(rep(0:0,len=201),rep(1:1,len=8),rep(2:2,len=1),rep(3:3,len=0),rep(4:4,len=0))

sart <- as.data.frame(HCT116)
sart1 <- as.data.frame(UL1)
                          
sart$Sample <- "HCT116"
sart1$Sample <- "hnRNPUL1"
names(sart1)[1] <- "SART3 Foci/cell"
      
names(sart)[1] <- "SART3 Foci/cell"

sartviolin <- rbind(sart,sart1)

t.test(sartviolin$`SART3 Foci/cell`[sartviolin$Sample=="HCT116"], sartviolin$`SART3 Foci/cell`[sartviolin$Sample=="hnRNPUL1"])


sartviolin%>%
  ggplot+
  aes(x=Sample,y=`SART3 Foci/cell`,fill=Sample)+
  ylab("SART3 Foci / Cell")+
   guides(fill=FALSE,color=FALSE)+
  theme_bw()+
  coord_cartesian(ylim=c(0,5.5))+
  scale_fill_manual(values=cbbPalette)+
  geom_violin(trim=TRUE,adjust=3,alpha=0.8)+
  geom_boxplot(width=.25,color="black",fill="white",alpha=0.5,outlier.shape=NA)+
  geom_segment(aes(x = 1, y = 5.25, xend = 2, yend = 5.25),size=0.5) +
  annotate("text",x = 1.5, y = 5.35, label = "***", size = 5) +
  geom_segment(aes(x = 1, y = 5.27, xend = 1, yend = 4.5))+ 
  geom_segment(aes(x = 2, y = 5.27, xend = 2, yend = 4.5))+
  theme(axis.title.x=element_blank(),
  axis.text.x=element_text(size=14),
  axis.text.y=element_text(size=14),
  axis.title.y=element_text(margin=margin(t=0,r=10,b=0,l=0)),
  text=element_text(size=17))

ggsave(file="./Sart3foci.png",dpi=300,units="in",width=3.5,height=3.5)
```

Gem Bodies

```{r, fig.height=3.5, fig.width=3.5}

HCT116 <- c(rep(0:0,len=86),rep(1:1,len=64),rep(2:2,len=57),rep(3:3,len=24),rep(4:4,len=8),rep(5:5,len=1))

UL1 <- c(rep(0:0,len=215),rep(1:1,len=16),rep(2:2,len=9))


cbodies <- as.data.frame(HCT116)
cbodies1 <- as.data.frame(UL1)
                          
cbodies$Sample <- "HCT116"
cbodies1$Sample <- "hnRNPUL1"
names(cbodies1)[1] <- "CB/cell"
      
names(cbodies)[1] <- "CB/cell"

violin <- rbind(cbodies,cbodies1)
t.test(violin$`CB/cell`[violin$Sample=="HCT116"], violin$`CB/cell`[violin$Sample=="hnRNPUL1"])


violin%>%
  ggplot+
  aes(x=Sample,y=`CB/cell`,fill=Sample)+
  ylab("Gem Bodies / Cell")+
  xlab("Cell line")+
  guides(fill=FALSE,color=FALSE)+
  theme_bw()+
    coord_cartesian(ylim=c(0,6.25))+
  scale_fill_manual(values=cbbPalette)+
  geom_violin(trim=TRUE,adjust=3,alpha=0.8)+
  geom_boxplot(width=.4,color="black",fill="white",alpha=0.6,outlier.shape=NA)+
  geom_segment(aes(x = 1, y = 6, xend = 2, yend = 6),size=0.5) +
  annotate("text",x = 1.5, y = 6.25, label = "***", size = 5) +
  geom_segment(aes(x = 1, y = 6.02, xend = 1, yend = 5.5),size=0.5)+ 
  geom_segment(aes(x = 2, y = 6.02, xend = 2, yend = 5.5),size=0.5)+
  theme(axis.title.x=element_blank(),
  axis.text.x=element_text(size=14),
  axis.text.y=element_text(size=14),
  axis.title.y=element_text(margin=margin(t=0,r=10,b=0,l=0)),
  text=element_text(size=17))

ggsave(file="./GemBodies.png",dpi=300,units="in",width=3.5,height=3.5)
```

Cajal Bodies minus / plus dox/aux

```{r, fig.height=4, fig.width=6}

HCT116 <- c(1,1,1,2,0,2,1,0,1,2,1,1,1,1,1,3,0,0,1,0,1,0,2,4,0,2,1,1,1,2,3,1,2,0,1,2,1,2,0,2,3,2,2,3,1,0,2,1,2,2,4,1,2,2,2,0,0,1,1,1,1,2,2,2,2,3,2,3,2,3,3,2,4,3,3,4,1,1,0,0,2,2,2,1,2,1,2,1,2,0,2,3,3,3,2,3,3,2,2,1,2,1,2,2,0,2,2,2,2,2,1,2,1,2,1,1,1,3,2,2,2,1,2,3,4,3,1,1,1,3,3,2,3,4,2,3,1,0,1,2,2,2,2,1,3,1,1,2,1,2,1,2,3,2,2,1,1,2,2,2,2,3,2,1,2,2,0,0,1,2,2,2,1,1,2,1,1,1,1,1)
UL1 <- c(0,1,3,1,2,0,2,2,3,1,1,0,2,2,2,2,0,2,1,1,1,1,2,1,2,1,2,1,2,2,1,2,2,1,1,2,2,1,0,0,1,0,1,2,2,1,0,2,1,0,0,0,1,0,2,2,3,1,1,1,2,1,2,2,1,1,1,0,1,1,3,1,0,3,0,0,1,3,4,3,1,1,1,1,0,1,1,3,2,0,2,1,2,1,2,2,1,2,1,2,1,0,2,2,3,2,1,1,0,1,1,0,1,1,2,2,1,0,2,2,4,2,4,3,2,2,3,2,3,2,2,2,1,3,3,2,1,1,2,4,2,3,3,3,2,1,1,1,3,2,1,2,3,4,1,1,3,2,3,5,2,2,3,3,1,2,1,2,1,1,2,4,4,3,3,4,0,0,0,3)
doxaux <- c(0,0,0,2,0,0,1,0,1,1,1,0,0,1,0,0,0,0,0,0,1,1,1,0,1,0,0,0,0,0,2,1,1,0,0,0,0,1,0,0,1,2,1,1,3,0,0,0,0,0,1,0,1,1,1,1,1,0,1,1,1,1,0,1,1,0,0,0,0,1,1,0,0,0,0,1,0,0,0,1,2,0,0,1,1,0,1,1,1,1,1,0,0,0,1,1,1,0,0,0,0,1,2,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,1,2,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,2,1,0,0,0,2,1,1,0,0,0,0,0,0,1,1,1)

cbodies <- as.data.frame(HCT116)
cbodies1 <- as.data.frame(UL1)
cbodies2 <- as.data.frame(doxaux)
                          
cbodies$Sample <- "HCT116"
cbodies1$Sample <- "hnRNPUL1 - Dox/Aux"
cbodies2$Sample <- "hnRNPUL1 + Dox/Aux"
names(cbodies1)[1] <- "CB/cell"
      
names(cbodies)[1] <- "CB/cell"
names(cbodies2)[1]<- "CB/cell"

violin <- rbind(cbodies,cbodies1,cbodies2)

  violin%>%
  ggplot+
  aes(x=Sample,y=`CB/cell`,fill=Sample)+
  scale_x_discrete(labels = function(x) str_wrap(x, width = 9))+
  ylab("Cajal Bodies / Cell")+
  xlab("Cell line")+
  guides(fill=FALSE,color=FALSE)+
  theme_bw()+
  scale_fill_manual(values=c('#E69F00','#009E73','#56B4E9'))+
  geom_violin(trim=TRUE,adjust=3,alpha=0.8)+
  geom_boxplot(width=.4,color="black",fill="white",alpha=0.6,outlier.shape=NA)+

    geom_segment(aes(x = 1, y = 5.75, xend = 2, yend = 5.75),size=0.5) +
  annotate("text",x = 1.5, y = 6, label = "n.s.", size = 5) +
  geom_segment(aes(x = 1, y = 5.3, xend = 1, yend = 5.75),size=0.5)+ 
  geom_segment(aes(x = 2, y = 5.3, xend = 2, yend = 5.75),size=0.5)+
  
  geom_segment(aes(x = 1, y = 6.5, xend =3, yend = 6.5),size=0.5) +
  annotate("text",x = 2, y = 6.75, label = "***", size = 5) +
    geom_segment(aes(x = 3, y = 6, xend = 3, yend = 6.5),size=0.5)+
    geom_segment(aes(x = 1, y = 6, xend = 1, yend = 6.5),size=0.5)+
  
  
  theme(axis.title.x=element_blank(),
  axis.text.x=element_text(size=14),
  axis.text.y=element_text(size=14),
  axis.title.y=element_text(margin=margin(t=0,r=3,b=0,l=0)),
  text=element_text(size=17))

ggsave(file="./CBPlusMinusDox.png",dpi=300,units="in",width=6,height=4)
  
```

