```{r}
ul1 <- read.csv("./metagene/matrix_K562_UL1.gz",sep="\t",header=F)
ul1 <- ul1[-1,]

drop <- c("V1","V2","V3","V4","V5","V6")
ul1 <- ul1[,!(names(ul1) %in% drop)]
ul1 <- ul1[rowSums(ul1) >1, , drop=FALSE]


ul2_n <- as.data.frame(t(apply(ul1,1,function(x) x/sum(x))))
ul2_n <- na.omit(ul2_n)


ul1_sum <- as.data.frame(colSums(ul2_n,))
ul1_sum$bin <- 1:700
ul1_sum$Sample <- "hnRNPUL1"
ul1_sum$`colSums(ul2_n, )` <- ul1_sum$`colSums(ul2_n, )`/sum(ul1_sum$`colSums(ul2_n, )`)
ul1_final <- ul1_sum

ul1 <- read.csv("./metagene/matrix_K562_Pol2_R_Myers.gz",sep="\t",header=F)
ul1 <- ul1[-1,]
drop <- c("V1","V2","V3","V4","V5","V6")
ul1 <- ul1[,!(names(ul1) %in% drop)]
ul1 <- ul1[rowSums(ul1) >1, , drop=FALSE]

ul2_n <- as.data.frame(t(apply(ul1,1,function(x) x/sum(x))))
ul2_n <- na.omit(ul2_n)

ul1_sum <- as.data.frame(colSums(ul2_n,))
ul1_sum$bin <- 1:700
ul1_sum$Sample <- "PolII (8WG16)"
ul1_sum$`colSums(ul2_n, )` <- ul1_sum$`colSums(ul2_n, )`/sum(ul1_sum$`colSums(ul2_n, )`)
pol2_final <- ul1_sum

metagene <- as.data.frame(rbind(ul1_final,pol2_final))
names(metagene)[1] <- "Sum"

metagene$Sum <- metagene$Sum*1000
```

```{r,fig.height=2,fig.width=4}
library(ggplot2)
library(dplyr)
cbbPalette <- c( "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
metagene%>%
ggplot() +
  aes(x=bin, y=Sum, col=Sample) +
  scale_colour_manual(values=cbbPalette)+
  geom_line(size=.65) + 
    theme_classic() +
    theme(plot.title=element_text(hjust=0,size=11)) +
    theme(axis.title.y=element_text(size = 10))+
  ylab("FC over Input ChIP-seq \nsignal over snRNA loci")+
  geom_vline(xintercept = c(100), linetype=2,
                color = "grey50", size=0.25)+
    geom_vline(xintercept = c(200), linetype=2,
                color = "grey50", size=0.25)+
  coord_cartesian(xlim=c(0,700))+
    theme(axis.text.x =(element_text(angle = 45, vjust = 1, hjust=1,colour="black")))+
  guides(color=guide_legend(override.aes=list(fill=NA)))+
  scale_x_continuous(name=NULL, breaks=c(0,100,200,700), labels=c("-100","TSS","TTS","+500"))
  
ggsave("./K562_ChIP_UL1Pol2_snRNAs.png",height=2,width=4,units="in")
```
