```{r}
library(dplyr)
ul1 <- read.csv("./ncbi/matrix_K562_UL1.gz",sep="\t",header=F)
ul1 <- ul1[-1,]

drop <- c("V1","V2","V3","V4","V5","V6")
ul1 <- ul1[,!(names(ul1) %in% drop)]

ul1_n <- ul1

ul1_n[is.na(ul1_n)]<-0 

ul1_sum <- as.data.frame(colSums(ul1_n,))
ul1_sum$bin <- 1:1700
ul1_sum$Sample <- "hnRNPUL1"
ul1_sum$`colSums(ul1_n, )` <- ul1_sum$`colSums(ul1_n, )`/sum(ul1_sum$`colSums(ul1_n, )`)

ul1_final_1 <- ul1_sum

names(ul1_final_1)[1] <- "Sum"

ul1 <- read.csv("./ncbi/matrix_K562_Pol2_R_Myers.gz",sep="\t",header=F)
ul1 <- ul1[-1,]

drop <- c("V1","V2","V3","V4","V5","V6")
ul1 <- ul1[,!(names(ul1) %in% drop)]

ul1_n <- ul1

ul1_n[is.na(ul1_n)]<-0 

ul1_sum <- as.data.frame(colSums(ul1_n,))
ul1_sum$bin <- 1:1700
ul1_sum$Sample <- "PolII"
ul1_sum$`colSums(ul1_n, )` <- ul1_sum$`colSums(ul1_n, )`/sum(ul1_sum$`colSums(ul1_n, )`)

pol2_final <- ul1_sum

names(pol2_final)[1] <- "Sum"
metagene <- rbind(ul1_final_1,pol2_final)
metagene$Sum <- metagene$Sum * (1/max(metagene$Sum)) 
```



```{r,fig.height=2,fig.width=4}
library(ggplot2)
library(dplyr)
cbbPalette <- c( "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
metagene%>%
ggplot() +
  aes(x=bin, y=Sum, col=Sample) +
  scale_colour_manual(values=cbbPalette)+
  geom_smooth(size=.65,n=1700,method="loess",span=0.05,alpha=0.25) + 
    theme_classic() +
    theme(plot.title=element_text(hjust=0,size=11)) +
      theme(axis.title.y=element_text(size = 10))+
  ylab("FC over Input ChIP-seq \nsignal over histone loci")+
  geom_vline(xintercept = c(200), linetype=2,
                color = "grey50", size=0.25)+
    geom_vline(xintercept = c(700), linetype=2,
                color = "grey50", size=0.25)+
  coord_cartesian(xlim=c(0,1700))+
    theme(axis.text.x =(element_text(angle = 45, vjust = 1, hjust=1,colour="black")))+
  guides(color=guide_legend(override.aes=list(fill=NA)))+
  scale_x_continuous(name=NULL, breaks=c(0,200,700,1700), labels=c("-200","TSS","TTS","+1kb"))
ggsave("./K562_ChIP_RepHistones.png",height=2,width=4,units="in")


```