
```{r}
library("readxl")
wt <- read_excel("./massspecwt.xlsx")
wa<- read_excel("./massspecwa.xlsx")

names(wa)[3] <- "Gene"
names(wt)[3] <- "Gene"

merged <- merge(wt,wa,by="Gene")

merged$`wtwa` <- merged$`iBAQ WT`/merged$`iBAQ WA`
merged$`iBAQ WT`<- log2(merged$`iBAQ WT`)


merged$note[merged$Gene=="SART3" | merged$Gene=="NKRF" | merged$Gene=="XRN2" | merged$Gene=="HNRNPUL1"] <- 1
merged$Gene[merged$Gene=="HNRNPUL1"] <- "hnRNPUL1"

merged$note1<- "Normal"
merged$note1[merged$Gene=="SART3" | merged$Gene=="NKRF" | merged$Gene=="XRN2"] <- "Noteworthy"
merged$note1[merged$Gene=="hnRNPUL1"] <- "UL1"

```


```{r,fig.height=4,fig.width=4}
library(ggplot2)
library(ggrepel)
ggplot(merged) + 
  aes(x=`iBAQ WT`, y=merged$wtwa) +
  geom_point(aes(x=merged$`iBAQ WT`, y=merged$wtwa,color=merged$note1), size = 3)+
  scale_colour_manual(values=c("grey60","red","purple"))+
  geom_text_repel(aes(label=ifelse(note>0,as.character(Gene),'')),hjust=0,vjust=0,size=4.25)+
  xlab("log2 WT iBAQ intensity")+
  ylab("WT iBAQ intensity / ΔWA iBAQ intensity")+ 
  theme_bw()+
  theme(legend.position = "none")+
  theme(axis.title=element_text(size=12))+
    theme(plot.title = element_text(size=9.5))
ggsave(".//massspec.png",height=4,width=4,units="in")
```

